- supervisor/debug.lisp
- supervisor/entry.lisp
- supervisor/serial.lisp
> fix pseudostream spelling

- system/packages.lisp
Stop asdf from erroring out during initial compile/load by implementing unexport.
> Unexport implementation.

- applications/editor.lisp
Although the original implementation was elegant, it was very memory and cpu intensive. This implementation now works in long buffers without bringin the system to a halt due to excess resource usage.
The implementation creates a string of the buffer from the point to the start of the buffer and searches it backwards for the first instance of (in-package that starts on a line.  The use of format to generate the string is due to the fact that move-sexp doesn't look like it ignores parens in strings.
> Reimplement buffer-current-package in a more efficient way.

- gui/compositor.lisp
- system/sequence.lisp
* Support for Control, Meta, Super and Hyper in non-Latin keymaps via :untranlated-modifiers flag
* Support for start, end, from-end et al in COUNT & COUNT-IF
> Extending keyboard layouts; &key arguments in COUNTs

- README.md
I think it seems like a good idea to have a prettier readme for incoming traffic. I have added headings, formatting, and the picture that comes up on #mezzano.
https://github.com/equwal/Mezzano
> Make the Readme look nicer

- net/dhcp.lisp
- net/package.lisp
- expanding the main loop
- new request and status codes
- ability to specify the interface
- add a custom mezzano server request option
> More DHCP changes

- file/fat32.lisp
> Add stream-read-sequence and stream-file-length. Fix small error.

- file/fat32.lisp
I have find this bug after rebuilding mezzano.
> Fix bug while opening files in open-using-host. 

- system/stuff.lisp
Implement the random subsystem based on WELL512. This includes the random-state structure, random-state functions and random.
> Implement the random subsystem.

- system/stuff.lisp
Change make-random-state:
1. Generate a fresh random state using get-universal-time as a seed.
2. When making copies of random state, create an independent copy by using copy-seq to copy the "bits" array.
3. Add error check for type of "state".
Change random:
1. Check type/value of "limit".
> Fix issues with random.

- README.md
This very minor change, along with changes to MBuild that I am providing, avoid confusion that occurred to me when building Mezzano the first time.  I thought it may help others too.
> Minor improvement to instructions

- doc/quickstart.md
Correct misleading information. Example of a case for modelessness?
> Address oversight

- file/cache.lisp
- file/disk.lisp
- file/ext.lisp
- file/fat32.lisp
- file/http.lisp
- ipl.lisp
Add read support for ext2 and ext3.
Refactor file systems
Add read-sector and write-sector.
> Add read for ext2/3 and refactor FSs

- net/dns.lisp
- net/tcp.lisp
- system/string.lisp
Remove duplicated function
Refactor tcp.lisp
Ignore non ACK packets when connection status is :closing
> Small refactor

- gui/input-drivers.lisp
- supervisor/ps2.lisp
Change ps2.lisp mouse configuration to enable scroll wheel input.
Change input-drivers convert mouse scroll wheel input to button 4 and 5 events.
> Add mouse scroll wheel as buttons 4 and 5.

- drivers/usb/buffers.lisp
- drivers/usb/hid-debug.lisp
- drivers/usb/hid-test.lisp
- drivers/usb/hid.lisp
- drivers/usb/logitech.lisp
- drivers/usb/mezzano-usb.asd
- drivers/usb/ohci-debug.lisp
- drivers/usb/ohci-test.lisp
- drivers/usb/ohci.lisp
- drivers/usb/packages.lisp
- drivers/usb/threads.lisp
- drivers/usb/usb-debug.lisp
- drivers/usb/usb-defs.lisp
- drivers/usb/usb-driver.lisp
- drivers/usb/usb.asd
- ipl.lisp
First USB Driver release, contains:
1. An OHCI (Open Host Controller Interface) driver
2. An USB Driver (Mid-level driver between OHCI driver and device drivers)
3. A HID Class Driver that only supports mice.
> Minimal USB Driver

- file/fat32.lisp
FAT12 and FAT16 root directories are not allocated using clusters, so
they can not be read/written using the usual read-file/write-file
routines.
> fat fs: Add code to handle root directories as special cases.

- disk/disk.lisp
- file/cache.lisp
- file/ext4.lisp
- file/fat32.lisp
Fix small errors in fat32 , cache
Don't display . and .. in directory
Refactor cache , disk
> ebrasca/fs Update

- file/fat32.lisp
fat32: Add helper function deallocate-file
> fat32 update

- drivers/usb/ehci-intel.lisp
- drivers/usb/mass-storage.lisp
- drivers/usb/mezzano-usb.asd
- drivers/usb/ohci.lisp
- drivers/usb/packages.lisp
- drivers/usb/usb-defs.lisp
- drivers/usb/usb-driver.lisp
Add EHCI driver for intel EHCI controller - USB 2.0.
Also add code to mass storage class driver to retry on time outs.
> USB: Add EHCI driver for intel.

- applications/filer.lisp
- applications/memory-monitor.lisp
- gui/basic-repl.lisp
- gui/compositor.lisp
- gui/desktop.lisp
- gui/font.lisp
- gui/image.lisp
- gui/music-player.lisp
- gui/package.lisp
- gui/theme.lisp
- gui/widgets.lisp
- gui/xterm.lisp
- ipl.lisp
Make it easier to change colours.
> Add trivial theme support

- ipl.lisp
This change depends on a change to MBuild/Makefile which adds the host
name ("REMOTE:") to home and source directory names.
This PR depends on a corresponding MBuild PR which updates Makefile to provide new definitions for the home and source directories.
> file-system: Update ipl.lisp to support file systems other than REMOTE.
